---
ci:
  autoupdate_schedule: quarterly

repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.20
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--output-format=concise]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3.11
