[build-system]
requires = [
    "setuptools >= 44.1.1",
    "setuptools_scm[toml] >= 4",
    "wheel >= 0.36",
]
build-backend = "setuptools.build_meta"

[project]
name = "casement"
description = "Useful functionality for managing Microsoft Windows."
authors = [{name = "Blur Studio", email = "opensource@blur.com"}]
license = {text = "LGPL-3.0"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft",
    "Operating System :: Microsoft :: Windows :: Windows 7",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
requires-python = ">=3.7"
dynamic = ["dependencies", "optional-dependencies", "version"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.scripts]
casement = "casement.cli:main"

[project.urls]
Homepage = "https://github.com/blurstudio/casement"
Source = "https://github.com/blurstudio/casement"
Issues = "https://github.com/blurstudio/casement/issues"

[tool.setuptools]
platforms = ["any"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ["requirements-dev.txt"]}
pil = {file = ["requirements-pil.txt"]}

[tool.setuptools.packages.find]
exclude = ["tests"]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/casement/version.py"
version_scheme = "release-branch-semver"

[tool.isort]
profile = "black"

[tool.ruff]
exclude = [
    "*.egg-info",
    "*.pyc",
    ".cache",
    ".eggs",
    ".git",
    ".tox",
    "__pycache__",
    "build",
    "dist",
]

line-length = 80
indent-width = 4
target-version = "py37"
output-format = "concise"

[tool.ruff.lint]
select = ["B", "C", "E", "F", "N", "W", "B9"]
ignore = [
    "E203",
    "E501",
    "E722",
    "B904",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use preserve quotes for strings.
quote-style = "preserve"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.deptry.package_module_name_map]
pillow = "PIL"

[tool.deptry.per_rule_ignores]
DEP002 = [
    # Dev dependencies are used for tox testing and are not directly imported
    "covdefaults",
    "coverage",
    "pytest",
    "ruff",
    "tox",
]

DEP003 = [
    # PyWin32 doesn't play well with deptry
    "win32con",
]
